version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - DB_DSN=postgres://r:postgres@user-db:5432/user_db?sslmode=disable

  food-service:
    build:
      context: .
      dockerfile: food-service/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      food-db:
        condition: service_healthy
    environment:
      - DB_DSN=postgres://r:postgres@food-db:5432/food_db?sslmode=disable

  user-db:
    image: postgres:15
    environment:
      POSTGRES_USER: r
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U r -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  food-db:
    image: postgres:15
    environment:
      POSTGRES_USER: r
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U r -d food_db"]
      interval: 5s
      timeout: 5s
      retries: 5
